# VERBOSE := 1
SINGLE_THREAD := 1
USE_PREBUILD := 1

EA_DIR := C:/Users/nari/AppData/Local/Arduino15/packages/esp8266/
HLIB_DIR := $(EA_DIR)/hardware/esp8266/2.3.0/libraries
ULIB_DIR := C:/Users/nari/documents/Arduino/libraries

LIBS := $(HLIB_DIR)/SPI
LIBS += $(HLIB_DIR)/ESP8266WiFi
LIBS += $(ULIB_DIR)/Adafruit-GFX-Library
LIBS += $(ULIB_DIR)/Adafruit_ILI9341-master
LIBS += $(ULIB_DIR)/Humblesoft_ILI9341

include makeEspArduino.mk

